### ISSUE TITLE
 Failed to resolve lib

### ISSUE THREAD

**Issue by daupawar** [UlrichRaab/rx-contacts#6]
Getting error 

Failed to resolve: de.ulrichraab:rx-contacts:1.1.3 

Added project to project gradle
```
repositories {
    maven {
       url 'https://dl.bintray.com/ulrichraab/maven'
    }
}
```
Added to module

```
dependencies {
    compile 'de.ulrichraab:rx-contacts:1.1.3'
}
```

**Comment by UlrichRaab** [comment]
This was a issue in the publish script. I had to update it and upload a new version of the lib. It should work now with version 1.1.4 (tested it on 3 computers). Sorry for the inconvenience.

**Comment by daupawar** [comment]
Thank you
